with
    source as (select * from {{ source('wdi', 'wdicsv') }}),
    renamed as (
        select
            {{ adapter.quote("Country Name") }},
            {{ adapter.quote("Country Code") }},
            {{ adapter.quote("Indicator Name") }},
            {{ adapter.quote("Indicator Code") }},
            {{ adapter.quote("1960") }},
            {{ adapter.quote("1961") }},
            {{ adapter.quote("1962") }},
            {{ adapter.quote("1963") }},
            {{ adapter.quote("1964") }},
            {{ adapter.quote("1965") }},
            {{ adapter.quote("1966") }},
            {{ adapter.quote("1967") }},
            {{ adapter.quote("1968") }},
            {{ adapter.quote("1969") }},
            {{ adapter.quote("1970") }},
            {{ adapter.quote("1971") }},
            {{ adapter.quote("1972") }},
            {{ adapter.quote("1973") }},
            {{ adapter.quote("1974") }},
            {{ adapter.quote("1975") }},
            {{ adapter.quote("1976") }},
            {{ adapter.quote("1977") }},
            {{ adapter.quote("1978") }},
            {{ adapter.quote("1979") }},
            {{ adapter.quote("1980") }},
            {{ adapter.quote("1981") }},
            {{ adapter.quote("1982") }},
            {{ adapter.quote("1983") }},
            {{ adapter.quote("1984") }},
            {{ adapter.quote("1985") }},
            {{ adapter.quote("1986") }},
            {{ adapter.quote("1987") }},
            {{ adapter.quote("1988") }},
            {{ adapter.quote("1989") }},
            {{ adapter.quote("1990") }},
            {{ adapter.quote("1991") }},
            {{ adapter.quote("1992") }},
            {{ adapter.quote("1993") }},
            {{ adapter.quote("1994") }},
            {{ adapter.quote("1995") }},
            {{ adapter.quote("1996") }},
            {{ adapter.quote("1997") }},
            {{ adapter.quote("1998") }},
            {{ adapter.quote("1999") }},
            {{ adapter.quote("2000") }},
            {{ adapter.quote("2001") }},
            {{ adapter.quote("2002") }},
            {{ adapter.quote("2003") }},
            {{ adapter.quote("2004") }},
            {{ adapter.quote("2005") }},
            {{ adapter.quote("2006") }},
            {{ adapter.quote("2007") }},
            {{ adapter.quote("2008") }},
            {{ adapter.quote("2009") }},
            {{ adapter.quote("2010") }},
            {{ adapter.quote("2011") }},
            {{ adapter.quote("2012") }},
            {{ adapter.quote("2013") }},
            {{ adapter.quote("2014") }},
            {{ adapter.quote("2015") }},
            {{ adapter.quote("2016") }},
            {{ adapter.quote("2017") }},
            {{ adapter.quote("2018") }},
            {{ adapter.quote("2019") }},
            {{ adapter.quote("2020") }},
            {{ adapter.quote("2021") }},
            {{ adapter.quote("2022") }},
            {{ adapter.quote("2023") }},
            {{ adapter.quote("2024") }}

        from source
    )
select *
from renamed
