wdi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      database: wdi
      schema: dbt_nickbrett1
      threads: 4
    prod:
      type: duckdb
      path: ../wdi.duckdb
      threads: 4
      