wdi:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5432
      user: postgres
      password: postgres
      dbname: wdi
      schema: public
      threads: 4
  target: dev
