version: 2.1

jobs:
  download_population:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout

      # Install rclone via curl
      - run:
          name: Install rclone
          command: |
            curl https://rclone.org/install.sh | sudo bash

      # Restore pip cache
      - restore_cache:
          keys:
            - pip-cache-{{ checksum "requirements.txt" }}

      # Install pip modules from requirements.txt
      - run:
          name: Install pip modules
          command: pip install -r requirements.txt

      # Save pip cache for subsequent builds
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-cache-{{ checksum "requirements.txt" }}

      # Run the population download script
      - run:
          name: Download Population Data
          command: python download_population.py

  download_wdi:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout

      # Install rclone
      - run:
          name: Install rclone
          command: |
            curl https://rclone.org/install.sh | sudo bash

      # Restore pip cache
      - restore_cache:
          keys:
            - pip-cache-{{ checksum "requirements.txt" }}

      # Install pip modules
      - run:
          name: Install pip modules
          command: pip install -r requirements.txt

      # Save pip cache
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-cache-{{ checksum "requirements.txt" }}

      # Run the WDI download script
      - run:
          name: Download WDI Data
          command: python download_wdi.py

  transform:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout

      # Install rclone
      - run:
          name: Install rclone
          command: |
            curl https://rclone.org/install.sh | sudo bash

      # Install sqlite3 (or other dependencies as needed)
      - run:
          name: Install sqlite3
          command: sudo apt-get update && sudo apt-get install -y sqlite3

      # Restore pip cache
      - restore_cache:
          keys:
            - pip-cache-{{ checksum "requirements.txt" }}

      # Install pip modules
      - run:
          name: Install pip modules
          command: pip install -r requirements.txt

      # Save pip cache
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-cache-{{ checksum "requirements.txt" }}

      # Run the populate script (which reads from Cloudflare R2)
      - run:
          name: Populate Databases
          command: python populate.py --use-duckdb

      # Run dbt deps inside the wdi directory
      - run:
          name: Run dbt deps
          command: |
            pushd wdi
            dbt deps
            popd

      # Run dbt run inside the wdi directory
      - run:
          name: Run dbt run
          command: |
            pushd wdi
            dbt run --target prod
            popd

      # Generate dbt docs inside the wdi directory
      - run:
          name: Generate dbt docs
          command: |
            pushd wdi
            dbt docs generate --target prod
            popd
      # Persist the wdi.duckdb file to the workspace
      - persist_to_workspace:
          root: .
          paths:
            - wdi.duckdb

  load:
    docker:
      - image: cimg/python:3.13
    steps:
      - checkout
      # Attach the workspace so that wdi.duckdb is available
      - attach_workspace:
          at: .
      # Restore and install pip cache/modules steps here...
      - restore_cache:
          keys:
            - pip-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Install pip modules
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: pip-cache-{{ checksum "requirements.txt" }}
      # Now run the DuckDB to SQLite export script, which can use wdi.duckdb
      - run:
          name: Export DuckDB to SQLite
          command: python duckdb2sqlite.py

workflows:
  download_transform_load:
    jobs:
      - download_population
      - download_wdi
      - transform:
          requires:
            - download_population
            - download_wdi
      - load:
          requires:
            - transform